main_app/tutu/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trains
  resources :routes

  get 'trains/index'

  # get 'routes/index'

  root 'trains#index'

  # root 'routes#index'

end

main_app/tutu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

main_app/tutu/app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
end

main_app/tutu/app/models/train.rb
class Train < ActiveRecord::Base
  validates :number, presence: true
end

main_app/tutu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

main_app/tutu/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end


  private

  def route_params
    params.require(:route).permit(:name)
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

main_app/tutu/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]
  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def train_params
    params.require(:train).permit(:number)
  end

  def set_train
    @train = Train.find(params[:id])
  end
end

main_app/tutu/app/helpers/application_helper.rb
module ApplicationHelper
end

main_app/tutu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

main_app/tutu/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= form_with(model: @route, local: true) do |form| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :route_name %>
  </div>

  <div class="actions">
    <%= form.submit 'Update' %>
  </div>
<% end %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

main_app/tutu/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new route', new_route_path %>

main_app/tutu/app/views/routes/new.html.erb
<h1>Create new route</h1>

<%= form_with(model: @route, local: true) do |form| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :route_name %>
  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>
<%= link_to 'Back', routes_path %>

main_app/tutu/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route name:</strong>
  <%= @route.name %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

main_app/tutu/app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= form_with(model: @train, local: true) do |form| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Update' %>
  </div>
<% end %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

main_app/tutu/app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new train', new_train_path %>

main_app/tutu/app/views/trains/new.html.erb
<h1>Create new train</h1>

<%= form_with(model: @train, local: true) do |form| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>
<%= link_to 'Back', trains_path %>

main_app/tutu/app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Train number:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>