l12/info/tutu/config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

l12/info/tutu/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true
end

l12/info/tutu/app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

l12/info/tutu/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]
  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private
  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number)
  end
end

l12/info/tutu/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

l12/info/tutu/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

l12/info/tutu/app/helpers/welcome_helper.rb
module WelcomeHelper
end

l12/info/tutu/app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station, local: true) do |form| %>
  <% if railway_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(railway_station.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
      <% railway_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :railway_station_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

l12/info/tutu/app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

l12/info/tutu/app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Show', railway_station %></td>
        <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %>

l12/info/tutu/app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

l12/info/tutu/app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

l12/info/tutu/app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= form_with(model: @train, local: true) do |form| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

l12/info/tutu/app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

l12/info/tutu/app/views/trains/new.html.erb
<h1>New Train</h1>

<%= form_with(model: @train, local: true) do |form| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>


<%= link_to 'Back', trains_path %>

l12/info/tutu/app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>

l12/info/tutu/app/views/welcome/index.html.erb
<h1>Welcome rails#index</h1>
<%= link_to 'Список станций', railway_stations_path %>